package models

import (
	"time"

	"github.com/google/uuid"
)

// Avatar represents a single avatar record in the system.
// It mirrors the avatars table and is used across all layers
// (repository -> service -> handlers).
type Avatar struct {
	// ID is the avatar UUID (PK, generated by the service before insert).
	ID uuid.UUID `json:"id"`

	// UserID is the owner of the avatar. Comes from the X-User-ID header.
	UserID string `json:"user_id"`

	// FileName is the original name of the uploaded file (for Content-Disposition).
	FileName string `json:"file_name"`

	// MimeType is the detected MIME type (image/jpeg, image/png, image/webp).
	MimeType string `json:"mime_type"`

	// SizeBytes is the size of the original file in bytes.
	SizeBytes int64 `json:"size"`

	// S3Key is the object key of the original image in S3/MinIO.
	S3Key string `json:"-"`

	// ThumbnailS3Keys maps thumbnail size ("100x100", "300x300") -> S3 key.
	// Stored in PostgreSQL as JSONB, empty until the worker finishes.
	ThumbnailS3Keys map[string]string `json:"thumbnails,omitempty"`

	// UploadStatus is the state of the upload to S3.
	// See UploadStatus* constants.
	UploadStatus UploadStatus `json:"upload_status"`

	// ProcessingStatus is the state of the async thumbnail generation.
	// See ProcessingStatus* constants.
	ProcessingStatus ProcessingStatus `json:"processing_status"`

	// CreatedAt is set by PostgreSQL (DEFAULT NOW()).
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is bumped on every UPDATE.
	UpdatedAt time.Time `json:"updated_at"`

	// DeletedAt is used for soft delete. nil = active.
	DeletedAt *time.Time `json:"-"`
}

type UploadStatus string

const (
	UploadStatusUploading UploadStatus = "uploading"
	UploadStatusUploaded  UploadStatus = "uploaded"
	UploadStatusFailed    UploadStatus = "failed"
)

type ProcessingStatus string

const (
	ProcessingStatusPending    ProcessingStatus = "pending"
	ProcessingStatusProcessing ProcessingStatus = "processing"
	ProcessingStatusCompleted  ProcessingStatus = "completed"
	ProcessingStatusFailed     ProcessingStatus = "failed"
)
