// Code generated by mockery v2.53.6. DO NOT EDIT.

package worker

import (
	context "context"

	models "github.com/max-marek-projects/avatars-service/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetAvatarByID provides a mock function with given fields: ctx, id
func (_m *MockStorage) GetAvatarByID(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarByID")
	}

	var r0 *models.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetAvatarByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarByID'
type MockStorage_GetAvatarByID_Call struct {
	*mock.Call
}

// GetAvatarByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorage_Expecter) GetAvatarByID(ctx interface{}, id interface{}) *MockStorage_GetAvatarByID_Call {
	return &MockStorage_GetAvatarByID_Call{Call: _e.mock.On("GetAvatarByID", ctx, id)}
}

func (_c *MockStorage_GetAvatarByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorage_GetAvatarByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_GetAvatarByID_Call) Return(_a0 *models.Avatar, _a1 error) *MockStorage_GetAvatarByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetAvatarByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Avatar, error)) *MockStorage_GetAvatarByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcessingStatus provides a mock function with given fields: ctx, id, status, thumbnails
func (_m *MockStorage) UpdateProcessingStatus(ctx context.Context, id uuid.UUID, status models.ProcessingStatus, thumbnails map[string]string) error {
	ret := _m.Called(ctx, id, status, thumbnails)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ProcessingStatus, map[string]string) error); ok {
		r0 = rf(ctx, id, status, thumbnails)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateProcessingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcessingStatus'
type MockStorage_UpdateProcessingStatus_Call struct {
	*mock.Call
}

// UpdateProcessingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status models.ProcessingStatus
//   - thumbnails map[string]string
func (_e *MockStorage_Expecter) UpdateProcessingStatus(ctx interface{}, id interface{}, status interface{}, thumbnails interface{}) *MockStorage_UpdateProcessingStatus_Call {
	return &MockStorage_UpdateProcessingStatus_Call{Call: _e.mock.On("UpdateProcessingStatus", ctx, id, status, thumbnails)}
}

func (_c *MockStorage_UpdateProcessingStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.ProcessingStatus, thumbnails map[string]string)) *MockStorage_UpdateProcessingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.ProcessingStatus), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockStorage_UpdateProcessingStatus_Call) Return(_a0 error) *MockStorage_UpdateProcessingStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateProcessingStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.ProcessingStatus, map[string]string) error) *MockStorage_UpdateProcessingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUploadStatus provides a mock function with given fields: ctx, id, status
func (_m *MockStorage) UpdateUploadStatus(ctx context.Context, id uuid.UUID, status models.UploadStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUploadStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.UploadStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateUploadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUploadStatus'
type MockStorage_UpdateUploadStatus_Call struct {
	*mock.Call
}

// UpdateUploadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status models.UploadStatus
func (_e *MockStorage_Expecter) UpdateUploadStatus(ctx interface{}, id interface{}, status interface{}) *MockStorage_UpdateUploadStatus_Call {
	return &MockStorage_UpdateUploadStatus_Call{Call: _e.mock.On("UpdateUploadStatus", ctx, id, status)}
}

func (_c *MockStorage_UpdateUploadStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.UploadStatus)) *MockStorage_UpdateUploadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.UploadStatus))
	})
	return _c
}

func (_c *MockStorage_UpdateUploadStatus_Call) Return(_a0 error) *MockStorage_UpdateUploadStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateUploadStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.UploadStatus) error) *MockStorage_UpdateUploadStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
