// Code generated by mockery v2.53.6. DO NOT EDIT.

package worker

import (
	context "context"

	models "github.com/max-marek-projects/avatars-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockConsumer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Close() *MockConsumer_Close_Call {
	return &MockConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConsumer_Close_Call) Run(run func()) *MockConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Close_Call) Return(_a0 error) *MockConsumer_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Close_Call) RunAndReturn(run func() error) *MockConsumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeDelete provides a mock function with given fields: ctx, handler
func (_m *MockConsumer) ConsumeDelete(ctx context.Context, handler func(context.Context, models.AvatarDeleteEvent) error) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, models.AvatarDeleteEvent) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_ConsumeDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeDelete'
type MockConsumer_ConsumeDelete_Call struct {
	*mock.Call
}

// ConsumeDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context , models.AvatarDeleteEvent) error
func (_e *MockConsumer_Expecter) ConsumeDelete(ctx interface{}, handler interface{}) *MockConsumer_ConsumeDelete_Call {
	return &MockConsumer_ConsumeDelete_Call{Call: _e.mock.On("ConsumeDelete", ctx, handler)}
}

func (_c *MockConsumer_ConsumeDelete_Call) Run(run func(ctx context.Context, handler func(context.Context, models.AvatarDeleteEvent) error)) *MockConsumer_ConsumeDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, models.AvatarDeleteEvent) error))
	})
	return _c
}

func (_c *MockConsumer_ConsumeDelete_Call) Return(_a0 error) *MockConsumer_ConsumeDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_ConsumeDelete_Call) RunAndReturn(run func(context.Context, func(context.Context, models.AvatarDeleteEvent) error) error) *MockConsumer_ConsumeDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeUpload provides a mock function with given fields: ctx, handler
func (_m *MockConsumer) ConsumeUpload(ctx context.Context, handler func(context.Context, models.AvatarUploadEvent) error) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, models.AvatarUploadEvent) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_ConsumeUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeUpload'
type MockConsumer_ConsumeUpload_Call struct {
	*mock.Call
}

// ConsumeUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context , models.AvatarUploadEvent) error
func (_e *MockConsumer_Expecter) ConsumeUpload(ctx interface{}, handler interface{}) *MockConsumer_ConsumeUpload_Call {
	return &MockConsumer_ConsumeUpload_Call{Call: _e.mock.On("ConsumeUpload", ctx, handler)}
}

func (_c *MockConsumer_ConsumeUpload_Call) Run(run func(ctx context.Context, handler func(context.Context, models.AvatarUploadEvent) error)) *MockConsumer_ConsumeUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, models.AvatarUploadEvent) error))
	})
	return _c
}

func (_c *MockConsumer_ConsumeUpload_Call) Return(_a0 error) *MockConsumer_ConsumeUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_ConsumeUpload_Call) RunAndReturn(run func(context.Context, func(context.Context, models.AvatarUploadEvent) error) error) *MockConsumer_ConsumeUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockConsumer) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockConsumer_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConsumer_Expecter) Ping(ctx interface{}) *MockConsumer_Ping_Call {
	return &MockConsumer_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockConsumer_Ping_Call) Run(run func(ctx context.Context)) *MockConsumer_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConsumer_Ping_Call) Return(_a0 error) *MockConsumer_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Ping_Call) RunAndReturn(run func(context.Context) error) *MockConsumer_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
