// Code generated by mockery v2.53.6. DO NOT EDIT.

package worker

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockObjectStorage) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockObjectStorage_Delete_Call {
	return &MockObjectStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockObjectStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockObjectStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStorage_Delete_Call) Return(_a0 error) *MockObjectStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockObjectStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, key
func (_m *MockObjectStorage) Download(ctx context.Context, key string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockObjectStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStorage_Expecter) Download(ctx interface{}, key interface{}) *MockObjectStorage_Download_Call {
	return &MockObjectStorage_Download_Call{Call: _e.mock.On("Download", ctx, key)}
}

func (_c *MockObjectStorage_Download_Call) Run(run func(ctx context.Context, key string)) *MockObjectStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStorage_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockObjectStorage_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_Download_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockObjectStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, r, size, contentType
func (_m *MockObjectStorage) Upload(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	ret := _m.Called(ctx, key, r, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = rf(ctx, key, r, size, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockObjectStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - contentType string
func (_e *MockObjectStorage_Expecter) Upload(ctx interface{}, key interface{}, r interface{}, size interface{}, contentType interface{}) *MockObjectStorage_Upload_Call {
	return &MockObjectStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, key, r, size, contentType)}
}

func (_c *MockObjectStorage_Upload_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string)) *MockObjectStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockObjectStorage_Upload_Call) Return(_a0 error) *MockObjectStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) error) *MockObjectStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
