// Code generated by mockery v2.53.6. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/max-marek-projects/avatars-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *MockPublisher) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPublisher_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPublisher_Expecter) Ping(ctx interface{}) *MockPublisher_Ping_Call {
	return &MockPublisher_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPublisher_Ping_Call) Run(run func(ctx context.Context)) *MockPublisher_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPublisher_Ping_Call) Return(_a0 error) *MockPublisher_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_Ping_Call) RunAndReturn(run func(context.Context) error) *MockPublisher_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PublishDelete provides a mock function with given fields: ctx, event
func (_m *MockPublisher) PublishDelete(ctx context.Context, event models.AvatarDeleteEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AvatarDeleteEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDelete'
type MockPublisher_PublishDelete_Call struct {
	*mock.Call
}

// PublishDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - event models.AvatarDeleteEvent
func (_e *MockPublisher_Expecter) PublishDelete(ctx interface{}, event interface{}) *MockPublisher_PublishDelete_Call {
	return &MockPublisher_PublishDelete_Call{Call: _e.mock.On("PublishDelete", ctx, event)}
}

func (_c *MockPublisher_PublishDelete_Call) Run(run func(ctx context.Context, event models.AvatarDeleteEvent)) *MockPublisher_PublishDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AvatarDeleteEvent))
	})
	return _c
}

func (_c *MockPublisher_PublishDelete_Call) Return(_a0 error) *MockPublisher_PublishDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishDelete_Call) RunAndReturn(run func(context.Context, models.AvatarDeleteEvent) error) *MockPublisher_PublishDelete_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUpload provides a mock function with given fields: ctx, event
func (_m *MockPublisher) PublishUpload(ctx context.Context, event models.AvatarUploadEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AvatarUploadEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUpload'
type MockPublisher_PublishUpload_Call struct {
	*mock.Call
}

// PublishUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - event models.AvatarUploadEvent
func (_e *MockPublisher_Expecter) PublishUpload(ctx interface{}, event interface{}) *MockPublisher_PublishUpload_Call {
	return &MockPublisher_PublishUpload_Call{Call: _e.mock.On("PublishUpload", ctx, event)}
}

func (_c *MockPublisher_PublishUpload_Call) Run(run func(ctx context.Context, event models.AvatarUploadEvent)) *MockPublisher_PublishUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AvatarUploadEvent))
	})
	return _c
}

func (_c *MockPublisher_PublishUpload_Call) Return(_a0 error) *MockPublisher_PublishUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishUpload_Call) RunAndReturn(run func(context.Context, models.AvatarUploadEvent) error) *MockPublisher_PublishUpload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
