// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"

	models "github.com/max-marek-projects/avatars-service/internal/models"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockService) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Close(ctx interface{}) *MockService_Close_Call {
	return &MockService_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockService_Close_Call) Run(run func(ctx context.Context)) *MockService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Close_Call) Return(_a0 error) *MockService_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Close_Call) RunAndReturn(run func(context.Context) error) *MockService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActiveUserAvatar provides a mock function with given fields: ctx, userID
func (_m *MockService) DeleteActiveUserAvatar(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActiveUserAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteActiveUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActiveUserAvatar'
type MockService_DeleteActiveUserAvatar_Call struct {
	*mock.Call
}

// DeleteActiveUserAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) DeleteActiveUserAvatar(ctx interface{}, userID interface{}) *MockService_DeleteActiveUserAvatar_Call {
	return &MockService_DeleteActiveUserAvatar_Call{Call: _e.mock.On("DeleteActiveUserAvatar", ctx, userID)}
}

func (_c *MockService_DeleteActiveUserAvatar_Call) Run(run func(ctx context.Context, userID string)) *MockService_DeleteActiveUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteActiveUserAvatar_Call) Return(_a0 error) *MockService_DeleteActiveUserAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteActiveUserAvatar_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteActiveUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAvatar provides a mock function with given fields: ctx, id, userID
func (_m *MockService) DeleteAvatar(ctx context.Context, id uuid.UUID, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAvatar'
type MockService_DeleteAvatar_Call struct {
	*mock.Call
}

// DeleteAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID string
func (_e *MockService_Expecter) DeleteAvatar(ctx interface{}, id interface{}, userID interface{}) *MockService_DeleteAvatar_Call {
	return &MockService_DeleteAvatar_Call{Call: _e.mock.On("DeleteAvatar", ctx, id, userID)}
}

func (_c *MockService_DeleteAvatar_Call) Run(run func(ctx context.Context, id uuid.UUID, userID string)) *MockService_DeleteAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteAvatar_Call) Return(_a0 error) *MockService_DeleteAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteAvatar_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockService_DeleteAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveAvatar provides a mock function with given fields: ctx, userID
func (_m *MockService) GetActiveAvatar(ctx context.Context, userID string) (*models.Avatar, io.ReadCloser, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveAvatar")
	}

	var r0 *models.Avatar
	var r1 io.ReadCloser
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Avatar, io.ReadCloser, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) io.ReadCloser); ok {
		r1 = rf(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_GetActiveAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveAvatar'
type MockService_GetActiveAvatar_Call struct {
	*mock.Call
}

// GetActiveAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) GetActiveAvatar(ctx interface{}, userID interface{}) *MockService_GetActiveAvatar_Call {
	return &MockService_GetActiveAvatar_Call{Call: _e.mock.On("GetActiveAvatar", ctx, userID)}
}

func (_c *MockService_GetActiveAvatar_Call) Run(run func(ctx context.Context, userID string)) *MockService_GetActiveAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetActiveAvatar_Call) Return(_a0 *models.Avatar, _a1 io.ReadCloser, _a2 error) *MockService_GetActiveAvatar_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_GetActiveAvatar_Call) RunAndReturn(run func(context.Context, string) (*models.Avatar, io.ReadCloser, error)) *MockService_GetActiveAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatarByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetAvatarByID(ctx context.Context, id uuid.UUID) (*models.Avatar, io.ReadCloser, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarByID")
	}

	var r0 *models.Avatar
	var r1 io.ReadCloser
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Avatar, io.ReadCloser, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) io.ReadCloser); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_GetAvatarByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarByID'
type MockService_GetAvatarByID_Call struct {
	*mock.Call
}

// GetAvatarByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) GetAvatarByID(ctx interface{}, id interface{}) *MockService_GetAvatarByID_Call {
	return &MockService_GetAvatarByID_Call{Call: _e.mock.On("GetAvatarByID", ctx, id)}
}

func (_c *MockService_GetAvatarByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_GetAvatarByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetAvatarByID_Call) Return(_a0 *models.Avatar, _a1 io.ReadCloser, _a2 error) *MockService_GetAvatarByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_GetAvatarByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Avatar, io.ReadCloser, error)) *MockService_GetAvatarByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatarMetadata provides a mock function with given fields: ctx, id
func (_m *MockService) GetAvatarMetadata(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarMetadata")
	}

	var r0 *models.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAvatarMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarMetadata'
type MockService_GetAvatarMetadata_Call struct {
	*mock.Call
}

// GetAvatarMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) GetAvatarMetadata(ctx interface{}, id interface{}) *MockService_GetAvatarMetadata_Call {
	return &MockService_GetAvatarMetadata_Call{Call: _e.mock.On("GetAvatarMetadata", ctx, id)}
}

func (_c *MockService_GetAvatarMetadata_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_GetAvatarMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetAvatarMetadata_Call) Return(_a0 *models.Avatar, _a1 error) *MockService_GetAvatarMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAvatarMetadata_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Avatar, error)) *MockService_GetAvatarMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields: ctx
func (_m *MockService) Health(ctx context.Context) models.HealthStatus {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 models.HealthStatus
	if rf, ok := ret.Get(0).(func(context.Context) models.HealthStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.HealthStatus)
	}

	return r0
}

// MockService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Health(ctx interface{}) *MockService_Health_Call {
	return &MockService_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockService_Health_Call) Run(run func(ctx context.Context)) *MockService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Health_Call) Return(_a0 models.HealthStatus) *MockService_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Health_Call) RunAndReturn(run func(context.Context) models.HealthStatus) *MockService_Health_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserAvatars provides a mock function with given fields: ctx, userID
func (_m *MockService) ListUserAvatars(ctx context.Context, userID string) ([]models.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserAvatars")
	}

	var r0 []models.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListUserAvatars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAvatars'
type MockService_ListUserAvatars_Call struct {
	*mock.Call
}

// ListUserAvatars is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) ListUserAvatars(ctx interface{}, userID interface{}) *MockService_ListUserAvatars_Call {
	return &MockService_ListUserAvatars_Call{Call: _e.mock.On("ListUserAvatars", ctx, userID)}
}

func (_c *MockService_ListUserAvatars_Call) Run(run func(ctx context.Context, userID string)) *MockService_ListUserAvatars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ListUserAvatars_Call) Return(_a0 []models.Avatar, _a1 error) *MockService_ListUserAvatars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListUserAvatars_Call) RunAndReturn(run func(context.Context, string) ([]models.Avatar, error)) *MockService_ListUserAvatars_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function with given fields: ctx, userID, r, fileName, contentType, size
func (_m *MockService) UploadAvatar(ctx context.Context, userID string, r io.Reader, fileName string, contentType string, size int64) (*models.Avatar, error) {
	ret := _m.Called(ctx, userID, r, fileName, contentType, size)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 *models.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string, string, int64) (*models.Avatar, error)); ok {
		return rf(ctx, userID, r, fileName, contentType, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string, string, int64) *models.Avatar); ok {
		r0 = rf(ctx, userID, r, fileName, contentType, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, string, string, int64) error); ok {
		r1 = rf(ctx, userID, r, fileName, contentType, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type MockService_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - r io.Reader
//   - fileName string
//   - contentType string
//   - size int64
func (_e *MockService_Expecter) UploadAvatar(ctx interface{}, userID interface{}, r interface{}, fileName interface{}, contentType interface{}, size interface{}) *MockService_UploadAvatar_Call {
	return &MockService_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, userID, r, fileName, contentType, size)}
}

func (_c *MockService_UploadAvatar_Call) Run(run func(ctx context.Context, userID string, r io.Reader, fileName string, contentType string, size int64)) *MockService_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(string), args[4].(string), args[5].(int64))
	})
	return _c
}

func (_c *MockService_UploadAvatar_Call) Return(_a0 *models.Avatar, _a1 error) *MockService_UploadAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UploadAvatar_Call) RunAndReturn(run func(context.Context, string, io.Reader, string, string, int64) (*models.Avatar, error)) *MockService_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
